# Data split approach

In [10]:
import os
import sys
from pathlib import Path

import pandas as pd
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 80)

cwd = Path.cwd().resolve()
REPO_ROOT = cwd if (cwd / "pyproject.toml").exists() else cwd.parent
assert (REPO_ROOT / "pyproject.toml").exists(), "Could not locate the repository root."
sys.path.insert(0, str(REPO_ROOT))

DATA_ROOT = Path(os.environ.get("BREXPERT_DATA_ROOT", REPO_ROOT.parent / "data")).resolve()
print(f"DATA_ROOT = {DATA_ROOT}")

DATA_ROOT = /mnt/sam1/data

## Step 1 — Load aggregated processed data

In [11]:
import glob

processed_csvs = sorted(glob.glob(str(DATA_ROOT / "processed" / "**" / "*.csv"), recursive=True))
agg_df = pd.concat([pd.read_csv(p) for p in processed_csvs], ignore_index=True)
print(f"{len(processed_csvs)} processed csvs, {len(agg_df)} rows, {agg_df['patient'].nunique()} unique patients")
agg_df[["id", "patient", "dataset", "modality", "birads"]].head()

12 processed csvs, 292553 rows, 29213 unique patients

,id,patient,dataset,modality,birads
0,3989160a-57d8-4d71-9f95-f5e27ec2ebae,AMBL-001,advanced-mri-lesions,mr,(1) negative
1,6d251657-8930-456b-a54e-855130eea1ef,AMBL-001,advanced-mri-lesions,mr,(4) suspicious
2,b5199304-55e2-49c0-8cbc-ff8de7212276,AMBL-001,advanced-mri-lesions,mr,(1) negative
3,a46a5ff3-32d0-41ff-8163-f0a15f5afc93,AMBL-001,advanced-mri-lesions,mr,(4) suspicious
4,f0a82ab1-af37-4cd8-8871-a1cfb9e7f9c8,AMBL-001,advanced-mri-lesions,mr,(4) suspicious

## Step 2 — Collapse BI-RADS into action-oriented categories

In [12]:
from scripts.split import convert_birads

agg_df["original_birads"] = agg_df["birads"]
agg_df["birads"] = agg_df["birads"].apply(convert_birads)
agg_df.groupby(["original_birads", "birads"]).size().rename("rows").reset_index()

,original_birads,birads,rows
0,(1) negative,healthy/routine,229911
1,(2) benign,healthy/routine,35315
2,(3) probably benign,probably benign (follow up),10570
3,(4) suspicious,suspicious/malignancy-likely (biopsy),5727
4,(5) highly suggestive of malignancy,suspicious/malignancy-likely (biopsy),11030

## Step 3 — Patient-level label inventory (before splitting)

In [13]:
patient_labels_df = agg_df[["patient", "modality", "birads"]].dropna().drop_duplicates()
label_counts = patient_labels_df.groupby(["modality", "birads"])["patient"].nunique().rename("patients")
print(f"{patient_labels_df['patient'].nunique()} unique patients across {len(label_counts)} (modality, birads) labels")
label_counts.sort_index()

29213 unique patients across 9 (modality, birads) labels

modality  birads
mg        healthy/routine                          23267
          probably benign (follow up)               2360
          suspicious/malignancy-likely (biopsy)     2928
mr        healthy/routine                           1682
          probably benign (follow up)                  6
          suspicious/malignancy-likely (biopsy)     1630
us        healthy/routine                            338
          probably benign (follow up)                347
          suspicious/malignancy-likely (biopsy)      735
Name: patients, dtype: int64

## Step 4 — Split configuration

In [14]:
import inspect

from utils.stratified_splitter import split_data_budgeted

split_defaults = inspect.signature(split_data_budgeted).parameters
print(f"val_total target: {split_defaults['val_total'].default} patients")
print(f"test_total target: {split_defaults['test_total'].default} patients")

val_total target: 200 patients
test_total target: 400 patients

## Step 5 — Run the greedy quota-based split

In [ ]:
import logging

logging.basicConfig(level=logging.INFO, format="%(message)s", force=True)

train_df, test_df, val_df = split_data_budgeted(agg_df)#, val_total=500, test_total=500)

=== PATIENT COUNTS PER LABEL ===
mg | healthy/routine                              : 23,267
mg | probably benign (follow up)                  : 2,360
mg | suspicious/malignancy-likely (biopsy)        : 2,928
mr | healthy/routine                              : 1,682
mr | probably benign (follow up)                  : 6
mr | suspicious/malignancy-likely (biopsy)        : 1,630
us | healthy/routine                              : 338
us | probably benign (follow up)                  : 347
us | suspicious/malignancy-likely (biopsy)        : 735

=== BUILDING TEST ===
TEST final: 400 patients

=== BUILDING VAL ===
VAL final: 200 patients

=== LEAKAGE CHECK ===
Train ∩ Val:  0
Train ∩ Test: 0
Val ∩ Test:   0

=== PATIENT DISTRIBUTION ===

split                                           test  train  val
modality birads
mg       healthy/routine                          85  23142   40
         probably benign (follow up)              40   2300   20
         suspicious/malignancy-likely (biopsy)    40   2868   20
mr       healthy/routine                          40   1622   20
         probably benign (follow up)               0      6    0
         suspicious/malignancy-likely (biopsy)    40   1570   20
us       healthy/routine                          75    223   40
         probably benign (follow up)              75    232   40
         suspicious/malignancy-likely (biopsy)   125    550   60

=== ROW DISTRIBUTION ===

split                                           test   train  val
modality birads
mg       healthy/routine                         158  247477  113
         probably benign (follow up)             100    9805   66
         suspicious/malignancy-likely (biopsy)    88    6609   65
mr       healthy/routine                          80   16694  108
         probably benign (follow up)               0      37    0
         suspicious/malignancy-likely (biopsy)   200    8556   66
us       healthy/routine                          75     446   75
         probably benign (follow up)              75     447   40
         suspicious/malignancy-likely (biopsy)   125     988   60

## Step 6 — Resulting split sizes

In [16]:
pd.DataFrame(
    {
        "patients": [df["patient"].nunique() for df in (train_df, val_df, test_df)],
        "rows": [len(df) for df in (train_df, val_df, test_df)],
    },
    index=["train", "val", "test"],
)

       patients    rows
train     28613  291059
val         200     593
test        400     901

## Step 7 — Leakage and completeness sanity checks

In [17]:
train_p, val_p, test_p = (set(df["patient"]) for df in (train_df, val_df, test_df))
print(f"train ∩ val: {len(train_p & val_p)} | train ∩ test: {len(train_p & test_p)} | val ∩ test: {len(val_p & test_p)}")

covered = train_p | val_p | test_p
print(f"patients covered by a split: {len(covered)} / {agg_df['patient'].nunique()} total")

train ∩ val: 0 | train ∩ test: 0 | val ∩ test: 0
patients covered by a split: 29213 / 29213 total

## Step 8 — Per-modality, per-BI-RADS distribution across splits

In [18]:
combined = pd.concat(
    [
        train_df.assign(split="train"),
        val_df.assign(split="val"),
        test_df.assign(split="test"),
    ]
)
combined.groupby(["modality", "birads", "split"])["id"].count().unstack(fill_value=0)

split                                           test   train  val
modality birads
mg       healthy/routine                         158  247477  113
         probably benign (follow up)             100    9805   66
         suspicious/malignancy-likely (biopsy)    88    6609   65
mr       healthy/routine                          80   16694  108
         probably benign (follow up)               0      37    0
         suspicious/malignancy-likely (biopsy)   200    8556   66
us       healthy/routine                          75     446   75
         probably benign (follow up)              75     447   40
         suspicious/malignancy-likely (biopsy)   125     988   60