# TOMPEI-CMMD preprocessing

In [1]:
import os
import sys
from pathlib import Path

import pandas as pd
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 80)

cwd = Path.cwd().resolve()
REPO_ROOT = cwd if (cwd / "pyproject.toml").exists() else cwd.parent
assert (REPO_ROOT / "pyproject.toml").exists(), "Could not locate the repository root."
os.chdir(REPO_ROOT)  
sys.path.insert(0, str(REPO_ROOT))

## Load raw data

In [2]:
from preprocessing.tompei_cmmd import TompeiCMMD, raw_imgs_path, raw_imgs_extension, csv_save_path
from utils.preprocessing import abbreviation_mapping, map_birads, get_value, normalize_laterality, region_mapping

ds = TompeiCMMD()
ds.set_dataset_name("tompei-cmmd")
ds.clinical_data.head()

,patient id,laterality,age,classification,exclusion reason,breast density,mass location,mass shape,mass margin,mass density,mass associated calcification,mass other associated findings,calcification location,calcification morphology,calcification distribution,calcification clearly benign calcifications,other associated findings,other findings location,other findings breast parenchyma,other findings skin,other findings lymph nodes,birads,notes,mass - additional lesion location,mass - additional lesion shape,mass - additional lesion margin,mass - additional lesion density,mass - additional lesion associated calcification,mass - additional lesion other associated findings,calcification - additional lesion location,calcification - additional lesion morphology,calcification - additional lesion distribution,calcification - additional lesion clearly benign calcifications
1,D1-0001,R,44.0,Benign,NaN,heterogeneous dense,NaN,NaN,NaN,NaN,NaN,NaN,M,Small Round Calcification,regional,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,D1-0002,L,40.0,Benign,NaN,heterogeneous dense,NaN,NaN,NaN,NaN,NaN,NaN,U-M,Small Round Calcification,regional,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,D1-0003,L,39.0,Benign,NaN,scattered,NaN,NaN,NaN,NaN,NaN,NaN,M,Amorphous and indistinct calcification,grouped,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,D1-0004,L,41.0,Benign,NaN,heterogeneous dense,NaN,NaN,NaN,NaN,NaN,NaN,M,Small Round Calcification,regional,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,D1-0005,R,42.0,Benign,NaN,extremely dense,NaN,NaN,NaN,NaN,NaN,NaN,L,Small Round Calcification,regional,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Step 1 — drop rows with an exclusion reason, then keep only rows with a known BI-RADS

In [3]:
ds.clinical_data = ds.clinical_data[ds.clinical_data["exclusion reason"].isna()]
ds.clinical_data = ds.clinical_data[ds.clinical_data["birads"].notna()]
ds.clinical_data["birads"] = ds.clinical_data["birads"].apply(lambda x: int(x))
ds.clinical_data.shape

(2429, 33)

### Step 2 — map laterality, BI-RADS, and the location fields to harmonized labels

In [4]:
ds.clinical_data["laterality"] = ds.clinical_data["laterality"].apply(lambda x: normalize_laterality(x) if pd.notna(x) else None)
ds.clinical_data["birads"] = ds.clinical_data["birads"].apply(lambda x: map_birads(x))
for col in ["mass location", "calcification location", "other findings location",
            "mass - additional lesion location", "calcification - additional lesion location"]:
    ds.clinical_data[col] = ds.clinical_data[col].apply(lambda x: get_value(x, region_mapping) if pd.notna(x) else None)
ds.clinical_data["birads"].value_counts(dropna=False)

birads
(1) negative                           1044
(5) highly suggestive of malignancy     660
(4) suspicious                          397
(3) probably benign                     249
(2) benign                               79
Name: count, dtype: int64

### Step 3 — lowercase all free-text columns, then expand known abbreviations

In [5]:
import re

ds.clinical_data = ds.clinical_data.apply(
    lambda col: col.str.lower() if col.dtype == "object" or col.dtype.name == "string" else col
)
pat = re.compile(r"\b(?:" + "|".join(map(re.escape, abbreviation_mapping.keys())) + r")\b")

ds.clinical_data = ds.clinical_data.map(lambda s: pat.sub(lambda m: abbreviation_mapping[m.group(0)], s) if isinstance(s, str) else s)

ds.clinical_data.head()

,patient id,laterality,age,classification,exclusion reason,breast density,mass location,mass shape,mass margin,mass density,mass associated calcification,mass other associated findings,calcification location,calcification morphology,calcification distribution,calcification clearly benign calcifications,other associated findings,other findings location,other findings breast parenchyma,other findings skin,other findings lymph nodes,birads,notes,mass - additional lesion location,mass - additional lesion shape,mass - additional lesion margin,mass - additional lesion density,mass - additional lesion associated calcification,mass - additional lesion other associated findings,calcification - additional lesion location,calcification - additional lesion morphology,calcification - additional lesion distribution,calcification - additional lesion clearly benign calcifications
1,D1-0001,right,44.0,Benign,NaN,heterogeneous dense,NaN,NaN,NaN,NaN,NaN,NaN,medial side (inner side of the breast),Small Round Calcification,regional,NaN,NaN,NaN,NaN,NaN,NaN,(2) benign,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,D1-0002,left,40.0,Benign,NaN,heterogeneous dense,NaN,NaN,NaN,NaN,NaN,NaN,upper-medial region (upper and inner side),Small Round Calcification,regional,NaN,NaN,NaN,NaN,NaN,NaN,(2) benign,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,D1-0003,left,39.0,Benign,NaN,scattered,NaN,NaN,NaN,NaN,NaN,NaN,medial side (inner side of the breast),Amorphous and indistinct calcification,grouped,NaN,NaN,NaN,NaN,NaN,NaN,(3) probably benign,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,D1-0004,left,41.0,Benign,NaN,heterogeneous dense,NaN,NaN,NaN,NaN,NaN,NaN,medial side (inner side of the breast),Small Round Calcification,regional,NaN,NaN,NaN,NaN,NaN,NaN,(2) benign,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,D1-0005,right,42.0,Benign,NaN,extremely dense,NaN,NaN,NaN,NaN,NaN,NaN,lower region (lower part of the breast),Small Round Calcification,regional,NaN,NaN,NaN,NaN,NaN,NaN,(2) benign,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Step 4 — keep only patients with exactly 2 images (one CC + one MLO)

In [6]:
from glob import glob
import os

ds.clinical_data["n_images"] = ds.clinical_data["patient id"].apply(
    lambda pid: len(glob(os.path.join(raw_imgs_path, pid.upper(), "**", f"*{raw_imgs_extension}"), recursive=True))
)
ds.clinical_data["n_images"].value_counts(dropna=False)

n_images
4    1423
2     643
0     363
Name: count, dtype: int64

In [7]:
ds.clinical_data = ds.clinical_data[ds.clinical_data["n_images"] == 2]
ds.clinical_data.shape

(643, 34)

In [8]:
set(ds.clinical_data["age"])

{17.0,
 18.0,
 23.0,
 24.0,
 26.0,
 27.0,
 28.0,
 29.0,
 30.0,
 31.0,
 32.0,
 33.0,
 34.0,
 35.0,
 36.0,
 37.0,
 38.0,
 39.0,
 40.0,
 41.0,
 42.0,
 43.0,
 44.0,
 45.0,
 46.0,
 47.0,
 48.0,
 49.0,
 50.0,
 51.0,
 52.0,
 53.0,
 54.0,
 55.0,
 56.0,
 57.0,
 58.0,
 59.0,
 60.0,
 61.0,
 62.0,
 63.0,
 64.0,
 65.0,
 66.0,
 67.0,
 68.0,
 69.0,
 70.0,
 71.0,
 72.0,
 73.0,
 74.0,
 75.0,
 78.0,
 80.0,
 82.0,
 83.0}

## Build exam records for one patient

In [9]:
row = ds.clinical_data.iloc[0]
exams = ds.process_row(row)
exams

[ExamInformation(id='1486552f-4e28-594c-a041-518eba0ef826', patient='tompei-cmmd-D1-0001', dataset='tompei-cmmd', modality='mammography', birads='(2) benign', race='asian', machine='GE Senographe DS mammography system', exam='../data/processed/tompei-cmmd/imgs/D1-0001-1486552f-4e28-594c-a041-518eba0ef826_imgs.npy', segmentation=None, context='{"patient":{"age":"40-49"},"exam":{"modality":"mammography","laterality":"right","view":"cranial caudal"}}', findings='{"breast":{"composition":"(c) the breasts are heterogeneously dense, which may obscure small masses"},"lesion status":"present","annotation scope":"complete","lesions":[{"finding type":"calcification","location":{"laterality":"right","coarse location":"medial"},"calcification details":{"type":"typically benign","type details":"round","distribution":"regional"},"is index":true,"lesion id":"L1"}],"assessment":{"birads":"(2) benign"}}', exam_id='tompei-cmmd-D1-0001', breast_id='tompei-cmmd-D1-0001-right', assessment_scope='exam_level'),
 ExamInformation(id='36f16464-9312-59b5-99f7-cf24208844ca', patient='tompei-cmmd-D1-0001', dataset='tompei-cmmd', modality='mammography', birads='(2) benign', race='asian', machine='GE Senographe DS mammography system', exam='../data/processed/tompei-cmmd/imgs/D1-0001-36f16464-9312-59b5-99f7-cf24208844ca_imgs.npy', segmentation=None, context='{"patient":{"age":"40-49"},"exam":{"modality":"mammography","laterality":"right","view":"mediolateral oblique"}}', findings='{"breast":{"composition":"(c) the breasts are heterogeneously dense, which may obscure small masses"},"lesion status":"present","annotation scope":"complete","lesions":[{"finding type":"calcification","location":{"laterality":"right","coarse location":"medial"},"calcification details":{"type":"typically benign","type details":"round","distribution":"regional"},"is index":true,"lesion id":"L1"}],"assessment":{"birads":"(2) benign"}}', exam_id='tompei-cmmd-D1-0001', breast_id='tompei-cmmd-D1-0001-right', assessment_scope='exam_level')]

## Final processed CSV

In [10]:
import json

final_df = pd.read_csv(csv_save_path)
print(f"patients before per-exam processing: {len(ds.clinical_data)} (x2 images each) | rows in final csv: {len(final_df)}")
final_df.head()

patients before per-exam processing: 643 (x2 images each) | rows in final csv: 1286

,id,patient,dataset,modality,birads,race,machine,exam,segmentation,context,findings,exam_id,breast_id,assessment_scope,n_segmentations
0,82f36be6-4eb4-479a-8091-c24ef0a729c5,tompei-cmmd-D1-0001,tompei-cmmd,mammography,(2) benign,asian,GE Senographe DS mammography system,../data/processed/tompei-cmmd/imgs/D1-0001-82f36be6-4eb4-479a-8091-c24ef0a72...,NaN,"{""patient"":{""age"":""40-49""},""exam"":{""modality"":""mammography"",""laterality"":""ri...","{""breast"":{""composition"":""(c) the breasts are heterogeneously dense, which m...",tompei-cmmd-D1-0001,tompei-cmmd-D1-0001-right,exam_level,0
1,5d6b901d-d958-470e-bae8-5e59acd6cc18,tompei-cmmd-D1-0001,tompei-cmmd,mammography,(2) benign,asian,GE Senographe DS mammography system,../data/processed/tompei-cmmd/imgs/D1-0001-5d6b901d-d958-470e-bae8-5e59acd6c...,NaN,"{""patient"":{""age"":""40-49""},""exam"":{""modality"":""mammography"",""laterality"":""ri...","{""breast"":{""composition"":""(c) the breasts are heterogeneously dense, which m...",tompei-cmmd-D1-0001,tompei-cmmd-D1-0001-right,exam_level,0
2,ded39f8e-e2d0-4a3e-8313-aada90eddd70,tompei-cmmd-D1-0002,tompei-cmmd,mammography,(2) benign,asian,GE Senographe DS mammography system,../data/processed/tompei-cmmd/imgs/D1-0002-ded39f8e-e2d0-4a3e-8313-aada90edd...,NaN,"{""patient"":{""age"":""40-49""},""exam"":{""modality"":""mammography"",""laterality"":""le...","{""breast"":{""composition"":""(c) the breasts are heterogeneously dense, which m...",tompei-cmmd-D1-0002,tompei-cmmd-D1-0002-left,exam_level,0
3,4758a354-6e4e-435a-9abc-f3d4c205ff2b,tompei-cmmd-D1-0002,tompei-cmmd,mammography,(2) benign,asian,GE Senographe DS mammography system,../data/processed/tompei-cmmd/imgs/D1-0002-4758a354-6e4e-435a-9abc-f3d4c205f...,NaN,"{""patient"":{""age"":""40-49""},""exam"":{""modality"":""mammography"",""laterality"":""le...","{""breast"":{""composition"":""(c) the breasts are heterogeneously dense, which m...",tompei-cmmd-D1-0002,tompei-cmmd-D1-0002-left,exam_level,0
4,e3c44672-53a6-41d6-8d80-e3691a7af81b,tompei-cmmd-D1-0003,tompei-cmmd,mammography,(3) probably benign,asian,GE Senographe DS mammography system,../data/processed/tompei-cmmd/imgs/D1-0003-e3c44672-53a6-41d6-8d80-e3691a7af...,NaN,"{""patient"":{""age"":""<40""},""exam"":{""modality"":""mammography"",""laterality"":""left...","{""breast"":{""composition"":""(b) there are scattered areas of fibroglandular de...",tompei-cmmd-D1-0003,tompei-cmmd-D1-0003-left,exam_level,0

In [11]:
sample = final_df.iloc[0]
print(json.dumps(json.loads(sample['context']), indent=2))
print(json.dumps(json.loads(sample['findings']), indent=2))

{
  "patient": {
    "age": "40-49"
  },
  "exam": {
    "modality": "mammography",
    "laterality": "right",
    "view": "cranial caudal"
  }
}
{
  "breast": {
    "composition": "(c) the breasts are heterogeneously dense, which may obscure small masses"
  },
  "lesion status": "present",
  "annotation scope": "complete",
  "lesions": [
    {
      "finding type": "calcification",
      "location": {
        "laterality": "right",
        "coarse location": "medial"
      },
      "calcification details": {
        "type": "typically benign",
        "type details": "round",
        "distribution": "regional"
      },
      "is index": true,
      "lesion id": "L1"
    }
  ],
  "assessment": {
    "birads": "(2) benign"
  }
}